// Generated by CoffeeScript 1.7.1
(function() {
  var Express, Mongo, app, _ipAddress, _port, _ref, _ref1;

  Express = require('express');

  Mongo = require('mongodb');

  app = Express();

  app.get('/', function(req, res) {
    return res.send('Nothing here yet!');
  });

  _ipAddress = (_ref = process.env.OPENSHIFT_NODEJS_IP) != null ? _ref : '127.0.0.1';

  _port = (_ref1 = process.env.OPENSHIFT_NODEJS_PORT) != null ? _ref1 : 8080;

  app.listen(_ipAddress, _port, function() {
    return console.log("Node server started");
  });

}).call(this);
