// Generated by CoffeeScript 1.7.1
(function() {
  var Express, Mongo, app;

  Express = require('express');

  Mongo = require('mongodb');

  app = Express();

  app.get('/', function(req, res) {
    return res.send('Nothing here yet!');
  });

  app.listen(8080, function() {
    return console.log("Node server started");
  });

}).call(this);
